name = "DAMMmodel"
uuid = "7af7f183-cd03-4039-bf6b-67ea3eb1648d"
authors = ["Alexandre A. Renchon"]
version = "0.1.6"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"

[compat]
DataFrames = "1.3.1"
GLMakie = "0.4.7"
Makie = "0.15.3"
LsqFit = "0.12.1"
UnicodeFun = "0.4.1"
julia = "1.7"
