name = "DAMMmodel"
uuid = "7af7f183-cd03-4039-bf6b-67ea3eb1648d"
authors = ["Alexis Renchon et al."]
version = "0.1.5"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.7"
LsqFit = "0.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
