name = "DAMMmodel"
uuid = "7af7f183-cd03-4039-bf6b-67ea3eb1648d"
authors = ["Alexandre A. Renchon"]
version = "0.1.18"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"

[compat]
DataFrames = "1.3.2"
DocStringExtensions = "0.8.6"
GLMakie = "0.6"
LsqFit = "0.12.1"
UnicodeFun = "0.4.1"
Unitful = "1.10.1"
UnitfulMoles = "0.1.1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
